### PR TITLE
tool: fix compilation error

### PR DESCRIPTION
**Pull request by NikitaPuzyryov**
Looks like it was broken since 88b94e1
```
../src/casync-tool.c: In function ‘verb_list’:
../src/casync-tool.c:1996:51: error: storage size of ‘tm’ isn’t known
                                         struct tm tm;
                                                   ^~
../src/casync-tool.c:1999:45: error: implicit declaration of function ‘localtime_r’ [-Werror=implicit-function-declaration]
                                         if (localtime_r(&t, &tm) &&
                                             ^~~~~~~~~~~
../src/casync-tool.c:1999:45: warning: nested extern declaration of ‘localtime_r’ [-Wnested-externs]
../src/casync-tool.c:2000:45: error: implicit declaration of function ‘strftime’ [-Werror=implicit-function-declaration]
                                             strftime(d, sizeof(d), "%Y-%m-%d %H:%M:%S", &tm) > 0)
                                             ^~~~~~~~
../src/casync-tool.c:2000:45: warning: incompatible implicit declaration of built-in function ‘strftime’
../src/casync-tool.c:2000:45: note: include ‘<time.h>’ or provide a declaration of ‘strftime’
../src/casync-tool.c:1996:51: warning: unused variable ‘tm’ [-Wunused-variable]
                                         struct tm tm;
                                                   ^~
```

### CODE REVIEW

**Comment by keszybz** [comment]
Right, localtime_r needs time.h.
