### PR TITLE
Ubuntu

### PR DESCRIPTION
**Pull request by zonque**
Two trivial changes to make casync build and work on Ubuntu 16.04 LTS.

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, are you sure the liblzma dep doesn't matter? IIRC old versions of liblzma weren't able to generate compressed files compatible with the "xz" tool. But I am pretty sure we should insist on that. Can you verify that your chunk files can be decompressed with unxz correctly? If so that patch can go in, otherwise I'd prefer not to, since we would create a compatibility problem for the future with that.

Regarding the second patch: we are currently using util.h as missing.h replacement, and it already contained a couple fs magic definitions. I added CGROUP2_SUPER_MAGIC there now too in 06ea4537512ce01c728400aeca845ad7d6ba7560. That patch can be dropped hence.

**Comment by zonque** [comment]
Sorry for the late reply.

Yes, the lzma version shipped on Ubuntu 16.04 LTS right now is `5.1.0alpha`. Files created by casync with that version can be unpacked using `unxz` just fine.

Rebased and pushed again now, with the 2nd hunk dropped and another one added for a different compilation error issue.
